name: SG_svile
author: Zeao
description: SurvivalGames plugin.
main: Zeao\sg\SGmain
version: 0.1dev
api: [3.0.0-ALPHA6, 3.0.1]
load: STARTUP

commands:
    sg:
        description: SurvivalGames main command. 
