name: SurvivalGames
author: Zeao
description: The Main SurvivalGames plugin, the official and soon may be bug free.
main: Zeao\Main
version: 1.0.1
api: [3.0.0-ALPHA6, 3.0.1]
LOAD: STARTUP

commands:
    sg:
        description: SurvivalGames main command. 
